fruits-lab/vitaminc

lexer.l
parser.y

This separates normal outputs from error messages so that redirections (>) can be better exploited.

Report error messages with std::cerr

---

ast.cpp

Code generation is not a phase of transformation, which means it should not modify the syntax tree.
Optimizations, which perform the transformations, will be handled in a separate phase.

Mark CodeGen as constant member function

---

Makefile
ast.hpp
parser.y

The _ast.cpp_ file provides classes or functions that are meant to be includes by others, such as _parser.y_.
It should be a header file rather than an implementation file.

Convert ast file to header file

---

.gitignore

Python environments are associated with our testing tool and the VS Code configurations are specific to my personal use of the editor. To maintain cleaner version control, these elements are being ignored.
For shared configurations, we can utilize the [.editorconfig](https://editorconfig.org/) file.
Feel free to extend the list of exclusions if there are additional editor-specific configurations that need to be ignored!

Ignore Python environments & VS Code configurations

---

Makefile
main.cpp
parser.y

By relocating the parser driver to _main.cpp_, we enhance its autonomy in handling compiler options and other non-parser-related logic.
This separation contributes to a clearer and more modular code structure.

Move parser driver to main.cpp

---

ast.hpp
main.cpp
parser.y

This adjustment ensures that the parser can stay focused on its primary responsibilities. Additionally, it helps minimize the potential for parsing failures, as errors related to analyses and transformations are separated from parsing errors.

Move analysis and transformation outside parser

---

Makefile

This adjustment is crucial if you want to utilize implicit rules, as others are not recognized by the Makefile.
For further details, please refer to:
https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html

Rename Makefile variables to adhere to convention

---

main.cpp

The misleading comment is reported in https://github.com/fruits-lab/VitaminC/pull/24#discussion_r1311206188.

Correct misleading comment

---

.github/workflows/ci.yml
main.cpp
scripts/install-cxxopts.sh
test/turnt.toml

This PR introduces a third party library, _cxxopts_, to effectively manage command line arguments.
Notably, this update enables the specification of an output file via the command line, and additionally offers the option to enable the dumping of the abstract syntax tree.

Read command line arguments

---

scripts/check-format.sh

Previously, all source files were passed to clang-format as a SINGLE file,
resulting in _clang-format_ reporting an error due to "no such file or directory."
> **Note** 
> Another possible approach to resolve this issue is to remove the quotes around the variable, allowing word splitting. However, this may trigger a warning from [ShellCheck](https://github.com/koalaman/shellcheck) (SC2086: Double quote to prevent globbing and word splitting).
Also, it is generally recommended to [quote variables almost always](https://unix.stackexchange.com/questions/171346/security-implications-of-forgetting-to-quote-a-variable-in-bash-posix-shells) for safety.

Fix check format script to recognize source files

---

src/ast.cpp

Unnamed namespaces are more versatile in modern C++, as they support even class declarations.
For in-depth information, please consult the following resource: [Unnamed/anonymous namespaces vs. static functions](https://stackoverflow.com/questions/154469/unnamed-anonymous-namespaces-vs-static-functions)

Use unnamed namespace instead of static

---

parser.y

To reproduce the issue, first, create a test file under the project root using the following command:
```sh
touch test.c
cat << EOF > test.c
int main() {
return -1 * 2;
}
EOF
```
Next, compile the test file with VitaminC.
As of now, we don't yet support unary `-`, resulting in the "syntax error" message:
```sh
./vitaminc < test.c
```
As you can see, this error message lacks detail and doesn't provide insights into the actual error.
This pull request introduces an improvement by enhancing the error message verbosity:
```sh
./vitaminc < test.c
```
With this change, the error message is now more informative and helps in diagnosing the issue.

Enhance error message verbosity

---

include/ast.hpp
include/type_checker.hpp
include/visitor.hpp
main.cpp
src/ast.cpp
src/type_checker.cpp

1. Take a look at `main.cpp` to see how the `TypeChecker` is being used.
2. In `src/type_checker.cpp`, you can find the logic for type checking. Compare the differences with the original `CheckType` functions that are located in each corresponding AST node. You should discover that Visitors may have state: the `ScopeStack` is no longer being passed as an argument.  
3. Examine `include/visitor.hpp` and read the comments. You should discover that each AST node has a corresponding `Visit()` function, and there are two kinds of Visitors based on the constancy of the AST node being passed.
4. Finally, review `include/ast.hpp`. Each AST node has two `Accept()` functions to accept the corresponding kind of Visitor, and their implementations in `src/ast.cpp` are all identical and …

Check type with the Visitor pattern

---

include/ast.hpp
include/type_checker.hpp
src/ast.cpp
src/type_checker.cpp

- Replace call to deprecated `TypeCheck`s with call to `Accept`
(fix #39 )
- Remove deprecated `TypeCheck`s
The `TypeChecker` encountered an issue where concrete binary expressions, such as `PlusExprNode`, were erroneously dispatched to the default implementation, resulting in no action being taken.
To resolve this, the `TypeChecker` has to implement the concrete binary expressions, explicitly dispatch them to the parent class `BinaryExprNode`.

Fix type checker calling deprecated type check

---

include/ast.hpp

When working with polymorphic objects in C++, it's important to be aware of the issue of slicing.
Slicing occurs because copy and move operations in C++ are non-virtual. This means that if you operate through polymorphism without caution, you risk losing derived class-specific data.
Consider the following example:
```c++
#include <iostream>
struct Base {};
struct Derived : public Base { int i = 0; };
int main() {
Derived d1{};
d1.i = 1;
Derived d2{};
d2.i = 2;
Base& d2_ref{d2};
d2_ref = d1;
// At first glance, it should make d2.i == d1.i == 1
// since d2_ref is an alias of d2, but surprisingly, d2.i remains 2.
// Sliced!
std::cout << d2.i << '\n';  // 2
return 0;
}
``` 
We attempt to assign a `Derived` object to a reference of the `Base` class.
This operation seems like it should make …

Avoid slicing on polymorphic objects

---

include/ast.hpp
include/ast_dumper.hpp
include/util.hpp
main.cpp
src/ast.cpp
src/ast_dumpr.cpp
src/util.cpp

This PR follows the same concept as #39, with the removal of deprecated `Dump` functions.
To improve code structure, I introduce a new object, `Indenter`, which handles indention details.
One potentially complex aspect is how we retrieve the `Op`s of `BinaryExprNode`s. This is accomplished using a hidden Visitor pattern. It's stateless and utilized only once in the `Visit` function of `BinaryExprNode`. As such, I've constructed it in-place rather than as a static global object or a data member of `AstDumpr`. For more details, please review the `OpGetter` class and its accompanying internal comments.

Dump with Visitor pattern

---

include/ast.hpp
src/ast_dumpr.cpp
src/qbe_ir_generator.cpp
src/type_checker.cpp

As discussed in issue #43, all AST nodes are meant to be pure data structures.
Additionally, in response to issue #39, suffixes have been removed.

Convert AST nodes to struct & remove suffix from public data members

---

Makefile
include/visitor.hpp
lexer.l
main.cpp
parser.y

- Fix Clang mismatch warning
```
include/ast.hpp:14:1: warning: 'AstNode' defined as a struct here but previously declared as a class; this is valid, but may result in linker errors under the Microsoft C++ ABI [-Wmismatched-tags]
struct AstNode {
^
include/visitor.hpp:9:1: note: did you mean struct here?
class AstNode;
^~~~~
struct
```
- Use cpp files instead of c files as suggested by Clang

Fix Clang warning and change C files to Cpp files

---

.github/workflows/ci.yml
Makefile

These two mainstream compilers may discover warnings that the other does not catch (an example in #47), so we'd like to run tests with both.
> [!note]
> I prefer to add the `-Werror` flag only when running tests in our CI environment.
This way, we don't have to fix all warnings during development at the first moment.
However, it appears that we cannot append _Makefile_ variables via the command line, as the [`override` directive](https://www.gnu.org/software/make/manual/html_node/Override-Directive.html) doesn't achieve what I have in mind.

Run tests with g++ and clang++

---

parser.y

The precedence had the same name as the token, while the former one is used as a placeholder for the precedence. Therefore, it's better for them to use different names to avoid possible confusion.
The `%prec IF_WITHOUT_ELSE` simply instructs Bison that the rule `IF '(' expr ')' stmt` has the same precedence as `IF_WITHOUT_ELSE`.
Please let me know if you have any advice or suggestions on the naming! :smile:

Rename precedence to resolve confusion

---

include/ast.hpp
include/ast_dumper.hpp
include/qbe_ir_generator.hpp
include/type_checker.hpp
include/visitor.hpp
parser.y
src/ast.cpp
src/ast_dumper.cpp
src/qbe_ir_generator.cpp
src/type_checker.cpp

Since we have an `expr_opt` non terminal node, we can merge `NullStmtNode` and `ExprStmtNode` into one.
```
6.8.3 Expression and null statements
Syntax
expression-statement:
expressionopt ;
```

Merge expression statement

---

.github/workflows/ci.yml
scripts/install-fmt.sh

The purpose of this PR is to install fmt headers, so that we can utilize format strings for our output.
- Initial build time for `fmt` is `3m 18s`. Build time `1m 27s` with `-j` flag
Currently, only jobs can be run in parallel for Github workflows, and steps parallel support is still TBD[1]. 😢 
[1] https://github.com/orgs/community/discussions/14484

Install fmt library

---

scripts/install-cxxopts.sh
scripts/install-qbe.sh

The compiled libraries are read-only (write-protected); therefore, even though we have the necessary permissions to remove the build folder, `rm` prompts for confirmation.
To prevent this interaction when running the script, we include the `-f` flag.

Remove the library folder without prompting

---

Makefile
parser.y

Previously, we encountered issues due to the lack of forward declaration for the lexing function `yylex`. Consequently, we resorted to including lex.yy.cpp directly in parser.y to access it. The initial problem stemmed from our inability to insert it into the correct position within yy.tab.hpp. Recently, I found that the `%code` directive is aptly suited for addressing this issue.
The current dependency is now one-way, with only lex.yy.cpp depending on y.tab.hpp. Modifications have been made to the Makefile to align with this adjustment.
For more information, refer to:
https://www.gnu.org/software/bison/manual/html_node/_0025code-Summary.html#index-_0025code-5

Resolve include dependency for lex.yy.cpp

---

.clang-tidy
.github/workflows/ci.yml
.gitignore
Makefile
scripts/check-tidy.sh

Incorporated the static analyzer "clang-tidy" into our project to improve code quality.
- Added a make target `tidy` to perform tidy checks on the entire project. The compilation database `compile_commands.json` is not required for this target as the Makefile already contains the necessary commands.
- Introduced a CI job to conduct tidy checks on the difference between _main_ (`GITHUB_BASE_REF`) and _HEAD_. We utilize [Bear](https://github.com/rizsotto/Bear) to generate the compilation database.
Additionally, a script is added for CI execution. This script is not intended for local user execution due to the following reasons:
1. `clang-tidy-diff` supports exit with a failure code when there are errors from version 17 or 18 onward. (The exact version is uncertain. For more details, please …

Lint with clang tidy

---

.clang-tidy
Makefile
include/ast.hpp
include/ast_dumper.hpp
include/operator.hpp
include/qbe/sigil.hpp
include/qbe_ir_generator.hpp
include/symbol.hpp
include/type.hpp
include/util.hpp
include/visitor.hpp
main.cpp
parser.y
src/ast_dumper.cpp
src/qbe_ir_generator.cpp
src/util.cpp

This pull request addresses linting errors reported by clang-tidy. Each commit message provides insight into the rationale behind the solution, offering an opportunity to learn best practices in C++. We encourage reviewers to go through each commit message to gain a deeper understanding. :laughing:
Additionally, the bug reported in #76 is resolved together with [Exclude generated files from tidy checks](https://github.com/fruits-lab/VitaminC/pull/78/commits/249d32aacc02829188ff9a60c5566007a521d902).
Resolves: #75
Resolves: #76

Resolve linting errors reported by clang tidy

---

scripts/check-tidy-diff.sh

Previously, clang-tidy-diff was applied to all changed files, including those under the test/ directory. However, these files are not production code and may contain unusual constructs. Therefore, we exclude them from the output of `git diff`, ensuring they are not checked by clang-tidy.
For more details, please refer to [Making 'git log' ignore changes for certain paths](https://stackoverflow.com/questions/5685007/making-git-log-ignore-changes-for-certain-paths/21079437#21079437).

Exclude test files from tidy check

---

include/ast.hpp
parser.y
src/ast_dumper.cpp
src/qbe_ir_generator.cpp
src/type_checker.cpp
test/typecheck/compound_stmt.c
test/typecheck/compound_stmt.exp

This enhancement allows for declarations and statements to interleave within compound statements.
I follow the reference manual, naming the "nodes" inside the compound statement as `item`.
> [!note]
> Previously, there was a discussion regarding the use of `std::visit` when dispatching on `std::variant`. Initially, `std::visit` was considered less readable (see https://github.com/fruits-lab/VitaminC/pull/56#discussion_r1418991588).
> Upon reconsideration, it was realized that the actual underlying type is irrelevant, as the types are polymorphic and always call the `Accept` function. Therefore, using `std::visit` hides unnecessary detail, which is preferable to verbose holding conditions using `std::holds_alternative`.
Resolves: #79

Mix declarations and statements in compound statement

---

scripts/install-cxxopts.sh
scripts/install-fmt.sh

By default, the tests of fmt and the examples/tests of cxxopts are also built during installation, which slows down our CI process. Since we will not run the fmt tests or those of cxxopts, building them is unnecessary.

Drop build of examples/tests of library to speed up installation

---

include/ast.hpp
include/ast_dumper.hpp
include/qbe_ir_generator.hpp
include/type_checker.hpp
include/visitor.hpp
parser.y
src/ast.cpp
src/ast_dumper.cpp
src/qbe_ir_generator.cpp
src/type_checker.cpp
test/typecheck/func_def.c
test/typecheck/func_def.exp

This PR only parse a function with no parameters. I will introduce function call and support parameters in future PRs.
Worth noting that this change create a new symbol table before parsing functions (storing function ids).
Related to #85

Parse function definition

---

Makefile
parser.y

`-Wcounterexample` generates the following example for solving conflicts.
```
Example: INCR expr • '+' expr
Shift derivation
expr
↳ 29: unary_expr
↳ 43: INCR expr
↳ 30: expr • '+' expr
Reduce derivation
expr
↳ 30: expr                    '+' expr
↳ 29: unary_expr
↳ 43: INCR expr •
...
```

Add bison flags to generate better error messages

---

src/qbe_ir_generator.cpp

While debugging loops and conditions in the QBE IR, I noticed that the labels for different types of loops were too similar. To enhance clarity and facilitate mapping back to the C source code, I have renamed the labels accordingly.
```
$ cat test/codegen/break_stmt.c.ssa
export function w $main() {
@start
%.1 =l alloc4 4
%.2 =w copy 0
storew %.2, %.1
%.3 =l alloc4 4
%.4 =w copy 0
storew %.4, %.3
@.while_pred.1
%.5 =w loadw %.1
%.6 =w copy 10
%.7 =w csltw %.5, %.6
jnz %.7, @.while_body.1, @.while_end.1
@.while_body.1
%.8 =w loadw %.1
%.9 =w copy 3
%.10 =w ceqw %.8, %.9
jnz %.10, @.if_then.2, @.if_end.2
@.if_then.2
jmp @.while_end.1
@.if_end.2
%.11 =w loadw %.3
%.12 =w copy 1
%.13 =w add %.11, %.12
storew %.13, %.3
%.14 =w loadw %.1
%.15 =w copy 1
%.16 =w add %.14, %.15
storew %.16, %.1 …
```

Prefix labels with the name of the statement

---

include/qbe_ir_generator.hpp
src/qbe_ir_generator.cpp

Two functions have been added to implement the indentation logic for labels and instructions, respectively. The pure `Write` function is retained for manual formatting purposes.
Every instruction should be indented by one level; label definitions and comments should not be indented.
> [!important]
> For future QBE IR generation, utilize `WriteLabel_` to write label definitions and `WriteInstr_` to write instructions. Both functions generate a single line, eliminating the need to manually add newline characters (`\n`) to your `format` calls. When writing parts of an instruction or multiple instructions, use `Write_` and remember to prepend each instruction with `kIndentStr` and enclose them with newlines.
Resolves: #99

Indent generated QBE IR

---

.clang-tidy
include/qbe/sigil.hpp
src/ast_dumper.cpp
src/qbe_ir_generator.cpp
src/type_checker.cpp
src/util.cpp

Occasionally, we may forget to include necessary headers or remove unnecessary ones. Enabling the include cleaner of clang tidy helps address this issue automatically.

Enable include cleaner of clang tidy

---

src/ast_dumper.cpp
src/qbe_ir_generator.cpp

Make code consistent across all visiting nodes, using `std::visit` for `loop_init_node`.

Use visit for loop initiate node

---

parser.y

Before implementing parameter list, adding type specifier may reduce future changes for `INT`.

Introduce type specifier

---

include/qbe_ir_generator.hpp
src/qbe_ir_generator.cpp

Handling the type and format of parameters should be done in the visit function of `ParamNode` rather than within `FuncDefNode`. This approach groups the logic more clearly and provides a clear indication of where to find related code.
Ideally, code generation related to a specific AST node should be performed within its visit function. Only in rare cases where information from the top level is required should generation be handled at a higher level.
Additionally, function definitions, whether with or without parameters, can be handled uniformly. The for loop simply does nothing if the parameter list is empty.

Move parameter generations to its visit function

---

Makefile
test/Makefile

Originally, our test tool, _Turnt_, didn't run in parallel even when the `-j` option was passed as a command line argument to `make test -j`. This was because the `MAKEFLAGS` variable never contained the `-j` option when checked. Based on my experimentation, it seems that the `-j` option is only added to the `MAKEFLAGS` after entering the recipe if it exists. Therefore, we need to check whether the `-j` option is passed inside the recipe. This also prevents the check from polluting the Makefile, as the variable `PARALLEL` is only used by the `test` target.
Additionally, I moved the checking logic down to the Makefile under `test/`. It is more suitable for such a Makefile to know how _Turnt_ works.

Fix Turnt not running in parallel when `-j` option is passed

---

include/ast.hpp
include/symbol.hpp
include/type.hpp
parser.y
src/ast_dumper.cpp
src/type.cpp
src/type_checker.cpp
test/typecheck/pointer.c
test/typecheck/pointer.exp
test/typecheck/pointer_param.c
test/typecheck/pointer_param.exp

This PR includes the following changes:
- Pointer variables declaration
- Function parameters, arguments as pointers
- Check pointer compatibility
- Create Type struct for both `Declnode` and `ExprNode`
- Update default Type for label identifier
Function pointer and pointer to pointer type will be added in future PRs. Also, Function return pointer type may require the feature of `malloc` and `free`, which are not supported yet.
See: #116

Support basic pointer features

---

include/ast.hpp
parser.y
src/ast_dumper.cpp
src/qbe_ir_generator.cpp
src/type_checker.cpp
test/typecheck/assignment_expr.exp
test/typecheck/compound_stmt.exp
test/typecheck/continue_stmt.exp
test/typecheck/do_while_single_stmt.exp
test/typecheck/do_while_stmt.exp
test/typecheck/for_nested_stmt.exp
test/typecheck/for_stmt.exp
test/typecheck/goto_stmt.exp
test/typecheck/if_else_nested_single_stmt.exp
test/typecheck/if_else_nested_stmt.exp
test/typecheck/if_else_single_stmt.exp
test/typecheck/if_else_stmt.exp
test/typecheck/if_single_stmt.exp
test/typecheck/pointer.c
test/typecheck/pointer.exp
test/typecheck/switch_stmt.exp
test/typecheck/unary_expr.exp
test/typecheck/while_single_stmt.exp
test/typecheck/while_stmt.exp

In order to support pointer dereference on the left hand side, such as `*ptr = 10`, this PR introduces assignment expression.
```
(6.5.16) assignment-expression:
conditional-expression
unary-expression assignment-operator assignment-expression
```

Refactor assignment expression

---

include/scope.hpp
src/type_checker.cpp
test/typecheck/goto_stmt.c
test/typecheck/goto_stmt.exp

- Each scope now associates with a `ScopeKind`. Please refer to _include/scope.hpp_: `struct Scope`.
- `ScopeStack::PushScope` and `ScopeStack::Add` now require a `ScopeKind`. Modifications have been made in `src/type_checker.cpp` to assign scope kinds to scopes and symbols.
- `ScopeStack` now supports merging the current scope with the next scope. This functionality is implemented in _include/scope.hpp_: `ScopeStack::MergeWithNextScope`.
- This enhancement specifically addresses including function parameters in the scope of the function body.
- The checking for "Use of undefined label" and "redefinition of label" now utilizes an auxiliary map. This change is implemented in _src/type_checker.cpp_: `<unnamed>::label_defined`.
- The undefined-check is performed just before the function …

Introduce concept of scope & Check whether label is defined

---

main.cpp
test/codegen/turnt.toml

- Output option will be used to name executable instead of IR file. I recommend using the legendary `a.out` as default. 😎 
- Add `target` option to specify the target IR. We only support `qbe` for now, we will support `llvm` in the future.

Generate executables directly

---

Makefile
main.cpp

- Fix clang tidy errors
- Clean `*.out` executables

Fix clang tidy

---

include/ast.hpp
include/type.hpp
parser.y
src/qbe_ir_generator.cpp
src/type.cpp

This pull request overhauls the grammar of declarations to accommodate complex types, such as function pointers. Additionally, the new grammar, being a proper subset of the one defined in the reference manual, facilitates the introduction of new kinds of declarations, such as `struct` and `union`.
To illustrate how a function definition is parsed, let's consider the example `int *a(int *x)`:
- `int`: The return type is parsed as the non-terminal `declarator_specifiers`.
- The `declarator_specifiers` derives to `type_specifier`, which ultimately stops at the terminal `INT`.
- `*a(int *x)`: The `*`, function name, and the parameters are parsed as the non-terminal `declarator`.
- The `*` is absorbed by the non-terminal `pointer_opt`, leaving the remaining `a(int *x)` to be parsed as …

Rewrite grammar of declaration to support complex types

---

lexer.l
parser.y

As I was implementing `struct` and `union`, I found the use for `const_expr`, so I might as well refactor expression grammar to match the C standard. Also, we can remove precedence of arithmetic operators, since the grammar has taken care of it.

Refactor expressions

---

include/ast.hpp
include/ast_dumper.hpp
include/qbe_ir_generator.hpp
include/type.hpp
include/type_checker.hpp
include/visitor.hpp
lexer.l
parser.y
src/ast.cpp
src/ast_dumper.cpp
src/qbe_ir_generator.cpp
src/type.cpp
src/type_checker.cpp
test/typecheck/struct.c
test/typecheck/struct.exp
test/typecheck/union.c
test/typecheck/union.exp

This PR parses struct and union type declaration.
- A new declaration node `RecordDeclNode` for struct and union.
- A new declaration node `FieldNode` for fields of struct or union.
- Introduces `StructType` and `UnionType`.
TODO: Just like we discusses, I will create a new symbol table (probably the same members but different name) under scope in the future PRs.
The output format is copied from clang:
```
$ clang -Xclang -ast-dump test/typecheck/struct.c
-FunctionDecl 0x55bf9d309910 <test/typecheck/struct.c:1:1, line:17:1> line:1:5 main 'int ()'
`-CompoundStmt 0x55bf9d309ed0 <col:12, line:17:1>
|-DeclStmt 0x55bf9d309aa0 <line:2:3, col:12>
| `-RecordDecl 0x55bf9d3099f8 <col:3, col:10> col:10 struct ss
|-DeclStmt 0x55bf9d309c98 <line:4:3, line:8:4>
| `-RecordDecl 0x55bf9d309ab8 <line:4:3, …
```

Parse struct and union

---

parser.y
test/typecheck/decl.exp
test/typecheck/struct.exp
test/typecheck/union.exp

My bad, missed this update on previous reviews. The current implementation only consider the case for `struct` and `union` variable initialization.

Fix missing record declaration tests

---

include/ast.hpp
include/ast_dumper.hpp
include/operator.hpp
include/qbe_ir_generator.hpp
include/type.hpp
include/type_checker.hpp
include/visitor.hpp
lexer.l
parser.y
src/ast.cpp
src/ast_dumper.cpp
src/qbe_ir_generator.cpp
src/type.cpp
src/type_checker.cpp
test/typecheck/array.exp
test/typecheck/array_param.exp
test/typecheck/struct.c
test/typecheck/struct.exp
test/typecheck/union.c
test/typecheck/union.exp

- Introduce a new struct `Field` for storing both id and `Type` for record members.
- Introduce a new class `RecordType` for sharing common methods for struct and union.
- Introduce a new AST node `RecordMemExprNode` for postfix record member access expression.
- Update dump info for `InitExprNode`.
P.S: I had added additional typecheck tests, but I haven't implemented any code generation for record declaration, so it will throw error `src/qbe_ir_generator.cpp:108: int {anonymous}::PrevExprNumRecorder::NumOfPrevExpr(): Assertion num_of_prev_expr_ != kNoRecord`. I can add additional expression tests after implementing code generation.
I can start implementing code generation for struct and union after this PR. 😄

Postfix record member access expression

---

src/type_checker.cpp

This PR addressed the redundant id check issue mentioned in #163, as whether the id is declared or not is already checked by the visit function of `IdExprNode`.
Additionally, I renamed a parameter that had confused me. We use abbreviations of AST node types for parameters in the visit function. However, the parameter for `RecordVarDeclNode` violates this convention, which caused confusion and made it seem like I was looking at the visit function for `RecordDeclNode`.

Remove redundant id check on function call

---

.github/workflows/ci.yml

This addresses the issue where missing includes are not caught until being merged. For a single push, we check the diff to ensure it doesn't introduce serious tidy issues. The diff check is relatively lightweight. For a PR, we perform a thorough check on the entire program to ensure everything is fine before merging into the codebase.

Check tidy entirely on PR & diff on push

---

include/type.hpp
src/llvm_ir_generator.cpp
src/type.cpp
src/type_checker.cpp

Since the `MemberType` function is a query function, it should not have to clone the type.
Note that the function is no longer `noexcept` after the change. Originally, it returned the `unknown` type when the `id` was not a member of the record. However, since we cannot make up such an unknown type as a temporary object and return its reference (undefined behavior), we have to throw an exception. This is acceptable because the type checker should already ensure that the member exists, thus querying with a non-existing `id` indicates some internal errors.

Return constant reference on query of member type

---

.github/workflows/ci.yml
Makefile
test/Makefile

Currently, we have three types of tests:
- Typecheck
- QBE codegen
- LLVM codegen
These tests are run together in CI, making it difficult to identify which part is causing a failure. This PR separates these tests into individual Makefile targets so they can be run independently in CI. The behavior of `make test` remains unchanged, as it will still run all tests.

Separate CI tests for QBE and LLVM

---

include/llvm/util.hpp
src/llvm/util.cpp
src/llvm_ir_generator.cpp

By not treating function pointers specially in `GetLLVMType`, most of the ad-hoc conversions from function types to pointer types are eliminated. The only remaining conversion is when referencing the ID of a function; the type of such ID expression should be a pointer type instead of a function type. Additionally, when using such an ID expression in a function call, we need to convert it back to a function type.

Reduce ad-hoc type conversions on functions

---

parser.y
src/llvm_ir_generator.cpp
src/qbe_ir_generator.cpp
src/type_checker.cpp

There is a common pattern in our code where we dynamically cast a pointer and assert that it is not null. This pattern implies that the cast should not fail. Therefore, we can use the reference version of dynamic casting, which throws a `std::bad_cast` exception if the cast fails.
Additionally, we are using dynamic casting with unique pointers, which requires a manual `get()` to obtain the underlying pointer. Since `get()` should only be used when necessary, this change also eliminates its use.
Notice that `static_cast` has been replaced by `dynamic_cast`. This is because there is a concern that the static cast might not be valid, so we are still relying on the dynamic check.
> [!NOTE]
> The remaining use cases are those where we use dynamic checks with an `if` to verify whether an object …

Use dynamic cast on reference when should not fail
